# Generated by Django 4.2.3 on 2023-10-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category_id', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=50, unique=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('available', models.BooleanField(default=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('vendor_code', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('country_of_manufacture', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('decoration', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('fastener', models.CharField(blank=True, max_length=50, null=True)),
                ('fabric_type', models.CharField(blank=True, max_length=50, null=True)),
                ('upper_material', models.CharField(blank=True, max_length=50, null=True)),
                ('filler_material', models.CharField(blank=True, max_length=50, null=True)),
                ('lining_material', models.CharField(blank=True, max_length=50, null=True)),
                ('model_features', models.CharField(blank=True, max_length=50, null=True)),
                ('fabric_features', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('composition', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('cut_features', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('price_segment', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.JSONField(blank=True, default=list, null=True)),
                ('quantity_in_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('picture1', models.CharField(blank=True, max_length=200, null=True)),
                ('picture2', models.CharField(blank=True, max_length=200, null=True)),
                ('picture3', models.CharField(blank=True, max_length=200, null=True)),
                ('picture4', models.CharField(blank=True, max_length=200, null=True)),
                ('picture5', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProducPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/$d/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['id'],
            },
        ),
    ]
