# Generated by Django 4.2.3 on 2023-10-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
